### ISSUE TITLE
PowerCommander Module only for Windows?

### ISSUE THREAD

**Issue by joergrenn** [Keeper-Security/keeper-sdk-dotnet#94]
Is the PowerCommander Module only compatible with Windows Operating systems or also with macOS or Linux?
Where would I need to install the module in macOS?
I tried using the module in macOS in Powershell 7.3.4 and after importing the moduel and running "kc" I get:

> InvalidOperation: keeper-sdk-dotnet-master/PowerCommander/AuthCommands.ps1:416
Line |
 416 |  … thFlow.Step -is [KeeperSecurity.Authentication.Sync.HttpProxyStep]) {
     |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to find type [KeeperSecurity.Authentication.Sync.HttpProxyStep].

**Comment by sk-keeper** [comment]
Thank you for letting us know that PowerCommander is broken. This issue is fixed.
Yes, PowerCommander works with MacOS.

**Comment by joergrenn** [comment]
Hello @sk-keeper,
I Downloaded the newest version and I am still getting the same error message.
I cannot confirm, that "kc" cmdlet works in Powershell 7.3.4 on macOS.

**Comment by sk-keeper** [comment]
The original message mentions `Unable to find type [KeeperSecurity.Authentication.Sync.HttpProxyStep` error
This `master` branch commit fixes this error.
https://github.com/Keeper-Security/keeper-sdk-dotnet/commit/637b69e0ff4e1ead814dfd7c03f34c1ab617c6a4

**Comment by joergrenn** [comment]
Hello @sk-keeper ,
I have cleared everything and downloaded again.
Now it works on my system, I must have overlooked something the last time.
Thanks a lot.
